# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source  'git@github.com:sunwei415/ipr-podspec.git'

target 'PDTSimpleCalendarDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for PDTSimpleCalendarDemo

  pod 'ipr-view-test-container', '~> 17.04.21.11'

  pod 'Reveal-SDK', '~> 8'
end
